version: '3.5'

services:
    gym-api:
        container_name: gym-api
        hostname: gym-api.localhost
        restart: always
        image: "hiagosama/php-nginx:latest"
        working_dir: /var/www/html/gym-api
        expose:
            - "9000"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            #- PHP_IDE_CONFIG:serverName=Xdebug
        volumes:
            - ./:/var/www/html/gym-api
            - ./docker/build/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - MyNetwork

networks:
    MyNetwork:
        driver: bridge
        name: MyNetwork
